<a href="https://colab.research.google.com/github/SonuThorave/AS/blob/main/ASSIGNMENT3_IRIS_USING_TENSERFLOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris

In [4]:
dataset=load_iris()

In [15]:
df=pd.DataFrame(dataset['data'],columns=dataset['feature_names'])
df['Species']=dataset['target']
df['Species']=df['Species'].apply(lambda x:dataset['target_names'][x])
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Species
0                5.1               3.5  ...               0.2   setosa
1                4.9               3.0  ...               0.2   setosa
2                4.7               3.2  ...               0.2   setosa
3                4.6               3.1  ...               0.2   setosa
4                5.0               3.6  ...               0.2   setosa

[5 rows x 5 columns]

In [16]:
X = df.iloc[:,0:3].values
y = df.iloc[:,4:].values

In [18]:
print(X[0:5])
print(y[0:5])

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]
[['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']]


In [19]:
print(X.shape)
print(y.shape)

(150, 3)
(150, 1)


In [20]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [21]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [22]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [25]:
print(X_train[0:5])

[[6.4 3.1 5.5]
 [5.4 3.  4.5]
 [5.2 3.5 1.5]
 [6.1 3.  4.9]
 [6.4 2.8 5.6]]


In [26]:
print(y_train[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [27]:
print(X_test[0:5])

[[5.8 2.8 5.1]
 [6.  2.2 4. ]
 [5.5 4.2 1.4]
 [7.3 2.9 6.3]
 [5.  3.4 1.5]]


In [28]:
print(y_test[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [29]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3)
  ])
model

In [30]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [31]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 4ms/step - loss: 5.9478 - accuracy: 0.3667
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 5.7768 - accuracy: 0.3667
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 5.6416 - accuracy: 0.3667
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 5.5070 - accuracy: 0.3667
Epoch 11/100
3/3 [===========

In [32]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 2.1490793228149414
Test accuracy: 0.20000000298023224


In [33]:
y_pred = model.predict(X_test)
y_pred

array([[ 0.10162406, -0.3498666 ,  0.24815995],
       [-0.2152987 , -0.07695189,  0.22915688],
       [-0.14965446, -0.06939793,  0.09490436],
       [ 0.02374216, -0.35066772,  0.30138385],
       [-0.17621416, -0.03369495,  0.10298071],
       [ 0.22628416, -0.48364523,  0.27846602],
       [-0.17923597, -0.02651193,  0.08896062],
       [-0.11567868, -0.19617277,  0.26465827],
       [-0.15706937, -0.16489285,  0.26549232],
       [-0.15789397, -0.13094476,  0.23729965],
       [ 0.10432341, -0.36729804,  0.2607637 ],
       [-0.07732377, -0.21601218,  0.25583607],
       [-0.03181774, -0.24421287,  0.24843037],
       [-0.13169296, -0.17345953,  0.25568134],
       [-0.01883916, -0.2554856 ,  0.24941918],
       [-0.1398376 , -0.05923411,  0.09645239],
       [-0.03439499, -0.23676619,  0.24402863],
       [ 0.01098912, -0.25498226,  0.22842091],
       [-0.21070427,  0.00410924,  0.09626284],
       [-0.18578058, -0.03328779,  0.08792856],
       [ 0.1065345 , -0.3447903 ,  0.240

In [34]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
