<a href="https://colab.research.google.com/github/SonuThorave/AS/blob/main/Loss_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ytrue=np.array([0.70,0,1,0.30,0.5])
ypred=np.array([1,0,0,1,1])

In [3]:
lerr=[]
def mean_absolute_error(ytrue,ypred):
  err=0
  global lerr
  for yt,yp in zip(ytrue,ypred):
    err+=abs(yt-yp)
   
    lerr.append(err)
  print('total error',err)
  mae=err/len(ytrue)
  return mae

me=mean_absolute_error(ytrue,ypred)
print('Mean absoute error is',me)

total error 2.5
Mean absoute error is 0.5


In [4]:
lerr

[0.30000000000000004, 0.30000000000000004, 1.3, 2.0, 2.5]

In [5]:
l1=[100,200,300]
l2=['a','b','c']
z=zip(l1,l2)
z

In [6]:
for v in z:
  print(v)

(100, 'a')
(200, 'b')
(300, 'c')


In [7]:
np.mean(np.abs(ytrue-ypred))

0.5

In [8]:
np.log(.99999999999)

-1.000000082745371e-11

In [9]:
ep=1e-15

In [10]:
ypred

array([1, 0, 0, 1, 1])

In [11]:
ypred_new =[max(i,ep) for i in ypred]
ypred_new

[1, 1e-15, 1e-15, 1, 1]

In [12]:
ypred_new =[min(i,1-ep)for i in ypred_new]
ypred_new

[0.999999999999999, 1e-15, 1e-15, 0.999999999999999, 0.999999999999999]

In [13]:
ypred_new=np.array(ypred_new)
ypred_new

array([1.e+00, 1.e-15, 1.e-15, 1.e+00, 1.e+00])

In [14]:
np.log(ypred_new)

array([-9.99200722e-16, -3.45387764e+01, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16])

In [15]:
-np.mean(ytrue * np.log(ypred_new) + (1-ytrue) *(1-np.log(ypred_new)))

-0.49999999999999944

In [16]:
def log_loss(ytrue,ypred):
  ep=1e-15
  ypred_new =[max(i,ep) for i in ypred]
  ypred_new =[min(i,1-ep)for i in ypred_new]
  ypred_new=np.array(ypred_new)
  return -np.mean(ytrue * np.log(ypred_new) + (1-ytrue) *(1-np.log(ypred_new)))

In [17]:
log_loss(ytrue,ypred)

-0.49999999999999944