<a href="https://colab.research.google.com/github/SonuThorave/AS/blob/main/simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential 
from keras.layers import Dense,SimpleRNN

In [2]:
def rnnModel():
  model=Sequential()
  model.add(SimpleRNN(2,input_shape=(3,1),activation='relu'))
  model.add(Dense(1,activation='relu'))
  model.compile(loss='mean_squared_error',optimizer='adam')
  return model

In [3]:
rnn_model=rnnModel()

In [4]:
rnn_model.weights

[<tf.Variable 'simple_rnn/simple_rnn_cell/kernel:0' shape=(1, 2) dtype=float32, numpy=array([[ 0.22575366, -1.3666035 ]], dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.6301533,  0.7764709],
        [-0.7764709,  0.6301532]], dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[ 0.685454 ],
        [-0.4595173]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [5]:
wx =rnn_model.get_weights()[0]
wh=rnn_model.get_weights()[1]
bh=rnn_model.get_weights()[2]
wy=rnn_model.get_weights()[3]
by=rnn_model.get_weights()[4]

In [6]:
print(f'wx= {wx} , wy ={wy} , bh={bh}, wh={wh} , by = {by}')

wx= [[ 0.22575366 -1.3666035 ]] , wy =[[ 0.685454 ]
 [-0.4595173]] , bh=[0. 0.], wh=[[ 0.6301533  0.7764709]
 [-0.7764709  0.6301532]] , by = [0.]


In [7]:
x=np.array([1,2,3])
x_input=np.reshape(x,[1,3,1])
y_pred=rnn_model.predict(x_input)
y_pred

array([[0.72070354]], dtype=float32)

In [8]:
x

array([1, 2, 3])

In [9]:
m=2
h0=np.zeros(m)
h1=np.dot(x[0],wx) +h0+bh
h2=np.dot(x[1],wx)+np.dot(h1,wh)+bh
h3=np.dot(x[2],wx) +np.dot(h2,wh)+bh
output=np.dot(h3,wy)+by
print(f'h1 = {h1} , h2= {h2} , h3={h3}')

h1 = [[ 0.22575366 -1.36660349]] , h2= [[ 1.65489459 -3.41908537]] , h3=[[ 4.37491857 -4.96938051]]


In [10]:
print(f'Output  from our calculation : {output}')

Output  from our calculation : [[5.2823218]]


In [11]:
print(f'output from network : {y_pred}')

output from network : [[0.72070354]]
